// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw4oCYOA5bOtdX0qTEf-CHFZvpFN2SIvA',
    appId: '1:845537553147:web:6277e489704152f0729e5e',
    messagingSenderId: '845537553147',
    projectId: 'final-project-e5f87',
    authDomain: 'final-project-e5f87.firebaseapp.com',
    storageBucket: 'final-project-e5f87.firebasestorage.app',
    measurementId: 'G-K95L7EN87L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoDufYI9TKOvh-cfyusAlAlpmzgxvFTNs',
    appId: '1:845537553147:android:5cb217e8c1ec541e729e5e',
    messagingSenderId: '845537553147',
    projectId: 'final-project-e5f87',
    storageBucket: 'final-project-e5f87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUDUAGIuWMP1V1l-zlqws78udoYx4K4rc',
    appId: '1:845537553147:ios:9b68a9044e2971de729e5e',
    messagingSenderId: '845537553147',
    projectId: 'final-project-e5f87',
    storageBucket: 'final-project-e5f87.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUDUAGIuWMP1V1l-zlqws78udoYx4K4rc',
    appId: '1:845537553147:ios:9b68a9044e2971de729e5e',
    messagingSenderId: '845537553147',
    projectId: 'final-project-e5f87',
    storageBucket: 'final-project-e5f87.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw4oCYOA5bOtdX0qTEf-CHFZvpFN2SIvA',
    appId: '1:845537553147:web:1f41fe4eeeb241f8729e5e',
    messagingSenderId: '845537553147',
    projectId: 'final-project-e5f87',
    authDomain: 'final-project-e5f87.firebaseapp.com',
    storageBucket: 'final-project-e5f87.firebasestorage.app',
    measurementId: 'G-0HXKQ9TY9T',
  );
}
